### ISSUE TITLE
update-search-index.hook bug

### ISSUE THREAD

**Issue by caadar** [nckx/palplus-hooks#1]
If full search index generation failed and just refresh the caches will happens, variable "${cave[@]}" is empty (cuz empty ${index_file}), so `exec search ""' fails.

It seems `local cave=( nice -n 19 ionice -c idle "${CAVE%% *}" )' string shuld be moved out from`if' condition scope.

**Comment by nckx** [comment]
Wow. Thanks for taking the time to report this! :smile: Unfortunately, I haven't used Exherbo for almost 2 years now. A glance at my profile shows why.

Also, a glance at the code makes me cringe a bit.

I'm not going to blindly shuffle lines of code about, but if you/anyone still find these scripts useful I'll gladly merge pull requests.
